CREATE TABLE [dbo].[COUNTRY_MASTER] (
    [ID]     INT            IDENTITY (1, 1) NOT NULL,
    [NAME]   NVARCHAR (255) NOT NULL,
    [CODE]   CHAR (10)      NOT NULL,
    [STATUS] INT            NOT NULL,
    CONSTRAINT [PK_KMI_COUNTRY_MASTER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

