CREATE TABLE [dbo].[DISTRICT_MASTER] (
    [ID]       INT           DEFAULT ('0') NOT NULL,
    [STATE_ID] INT           DEFAULT (NULL) NULL,
    [NAME]     VARCHAR (100) DEFAULT (NULL) NULL,
    [STATUS]   INT           NULL,
    CONSTRAINT [PK_DISTRICT_MASTER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

