CREATE TABLE [dbo].[LOG_COUNT] (
    [ID]       INT            IDENTITY (1, 1) NOT NULL,
    [USER_ID]  NVARCHAR (500) NULL,
    [LOG_DATE] DATETIME       NULL,
    CONSTRAINT [PK_LOG_COUNT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

